name = "freenavi"
main = "worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "out"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_SITE_URL = "https://freenavi.toromonja.com"
